### ISSUE TITLE
Question about templates

### ISSUE THREAD

**Issue by ImNobody422** [MasqueCrow/Blog-Project#1]
Sorry to bother.

Why post_draft_list page using the same source code as post_list.html?

It should have "created:" on the page, instead of "Published on: "

**Comment by ImNobody422** [comment]
Sorry, didn't notice you using `redirect_field_name = 'blog/post_list.html'`.

I use `redirect_field_name = 'blog/post_draft_list.html'`, can not get to the draft list page.

**Comment by anuragxgupta** [comment]
There seem to be some issue. Even I'm also facing same issue. 
**post_list.html** is getting opened everytime instead of **post_draft_view.html** when clicking on Draft button.
I tried changing **redirect_field_name** but not working. 
Please comment if that issue got resolved. 
Thanks in advance.
